import { createActions } from 'redux-actions';
import { Store } from 'redux';

export const TYPES = {
    ADD_APPLICATION: 'ADD_APPLICATION',

    PAUSE_APP_DOWNLOAD_AND_INSTALLATION: 'PAUSE_APP_DOWNLOAD_AND_INSTALLATION',
    CANCEL_APP_DOWNLOAD_AND_INSTALLATION:
        'CANCEL_APP_DOWNLOAD_AND_INSTALLATION',
    RESUME_APP_DOWNLOAD_AND_INSTALLATION:
        'RESUME_APP_DOWNLOAD_AND_INSTALLATION',

    DOWNLOAD_AND_INSTALL_APP_PENDING: 'DOWNLOAD_AND_INSTALL_APP_PENDING',
    DOWNLOAD_AND_INSTALL_APP_SUCCESS: 'DOWNLOAD_AND_INSTALL_APP_SUCCESS',
    DOWNLOAD_AND_INSTALL_APP_FAILURE: 'DOWNLOAD_AND_INSTALL_APP_FAILURE',

    UNINSTALL_APP_PENDING: 'UNINSTALL_APP_PENDING',
    UNINSTALL_APP_SUCCESS: 'UNINSTALL_APP_SUCCESS',
    UNINSTALL_APP_FAILURE: 'UNINSTALL_APP_FAILURE',

    CHECK_FOR_UPDATE_FOR: 'CHECK_FOR_UPDATE_FOR',
    SET_CURRENT_VERSION: 'SET_CURRENT_VERSION',
    SET_NEXT_VERSION: 'SET_NEXT_VERSION',

    UPDATE_DOWNLOAD_PROGRESS: 'UPDATE_DOWNLOAD_PROGRESS'
};

let currentStore: Store;

export const getCurrentStore = (): Store => currentStore;
export const setCurrentStore = ( passedStore: Store ): void => {
    currentStore = passedStore;
};

export const {
    addApplication,

    cancelAppDownloadAndInstallation,
    pauseAppDownloadAndInstallation,
    resumeAppDownloadAndInstallation,

    downloadAndInstallAppPending,
    downloadAndInstallAppSuccess,
    downloadAndInstallAppFailure,

    uninstallAppPending,
    uninstallAppSuccess,
    uninstallAppFailure,

    checkForUpdateFor,
    setCurrentVersion,
    setNextVersion,

    updateDownloadProgress
} = createActions(
    TYPES.ADD_APPLICATION,

    TYPES.CANCEL_APP_DOWNLOAD_AND_INSTALLATION,
    TYPES.PAUSE_APP_DOWNLOAD_AND_INSTALLATION,
    TYPES.RESUME_APP_DOWNLOAD_AND_INSTALLATION,

    TYPES.DOWNLOAD_AND_INSTALL_APP_PENDING,
    TYPES.DOWNLOAD_AND_INSTALL_APP_SUCCESS,
    TYPES.DOWNLOAD_AND_INSTALL_APP_FAILURE,

    TYPES.UNINSTALL_APP_PENDING,
    TYPES.UNINSTALL_APP_SUCCESS,
    TYPES.UNINSTALL_APP_FAILURE,

    TYPES.CHECK_FOR_UPDATE_FOR,
    TYPES.SET_CURRENT_VERSION,
    TYPES.SET_NEXT_VERSION,

    TYPES.UPDATE_DOWNLOAD_PROGRESS
);
